name: Build - Pull request
on:
  pull_request:

jobs:
  build_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0
          
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.91.2"

      - name: Building hugo
        run: hugo --minify
