name: Deployment pipeline

on:
  push:
    tags:
      - "v*"

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.91.2"

      - name: Building hugo
        run: hugo --minify

      - name: copy files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME_VM }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: './public'
          target: "/home/ktamariz"

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
